### ISSUE TITLE
Use strongly-typed attribute for dependencies that are typed

### ISSUE THREAD

**Issue by sbellware** [eventide-project/subst-attr#2]

**Comment by ntl** [comment]
This doesn't seem correct. In ruby, an object can be substitutable for another even if they don't share a common class ancestry. We leverage this all the time with substitutes, which are frequently _not_ subclasses of the class they're substitutable for. An untyped attribute is more in line with ruby's philosophy of duck typing.

**Comment by sbellware** [comment]
Right on. I was unconvinced of this one. Happy to be waved off!
